#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_modules.tests_sources = []

env_tests_modules = env_modules.Clone()

# We must disable the THREAD_LOCAL entirely in doctest to prevent crashes on debugging
# Since we link with /MT thread_local is always expired when the header is used
# So the debugger crashes the engine and it causes weird errors
# Explained in https://github.com/onqtam/doctest/issues/401
if env_tests_modules["platform"] == "windows":
    env_tests_modules.Append(CPPDEFINES=[("DOCTEST_THREAD_LOCAL", "")])

if env["disable_exceptions"]:
    env_tests_modules.Append(CPPDEFINES=["DOCTEST_CONFIG_NO_EXCEPTIONS_BUT_WITH_ALL_ASSERTS"])

env_tests_modules.add_source_files(env_modules.tests_sources, "*.cpp")
